language: csharp
solution: MakeRuler.sln
script:
  - xbuild /p:Configuration=Release MakeRuler.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./MakeRuler.Tests/bin/Release/MakeRuler.Tests.dll
