language: csharp
solution: MakeRuler.sln
install:
  - nuget restore MakeRuler.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MakeRuler.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MakeRuler.Tests/bin/Release/MakeRuler.Tests.dll
